### ISSUE TITLE
请问商店可以提供 mosdns 的安装吗？

### ISSUE THREAD

**Issue by qingtian110** [linkease/istore-repo#424]
mosdns 它单纯是一个 dns 服务器。它和 adg 是一样性质的。和科学上网无关联的。

**Comment by qingtian110** [comment]
@jjm2473 @xiangfeidexiaohuo

**Comment by xiangfeidexiaohuo** [comment]
> mosdns 它单纯是一个 dns 服务器。它和 adg 是一样性质的。和科学上网无关联的。

去那个第三方库 安装吧，这个不好上架的，违规。

**Comment by xiangfeidexiaohuo** [comment]
> > > mosdns 它单纯是一个 dns 服务器。它和 adg 是一样性质的。和科学上网无关联的。
> > 
> > 
> > 去那个第三方库 安装吧，这个不好上架的，违规。
> 
> 啊？ mosdns 也被定义成和passwall 同类插件的么

yes
