### ISSUE TITLE
有没有resilio sync的包，球球大神救救孩子吧

### ISSUE THREAD

**Issue by CD-D** [linkease/istore-repo#43]
路由器是华硕AX88U   aarch64 ARMv8 架构

**Comment by CD-D** [comment]
感谢大佬帮忙，但我这个架构好像安装不上docker，opkg install docker没有这个包。
去仓库找的版本也装不上，提示架构不兼容。
包地址：https://openwrt.pkgs.org/21.02/openwrt-packages-aarch64_cortex-a72/docker_20.10.16-1_aarch64_cortex-a72.ipk.html

**Comment by jjm2473** [comment]
resilio sync不是开源软件，如果官方没有openwrt的包，你的设备又没有docker，那基本就不用尝试了。
如果你熟悉linux，可以使用chroot模仿docker来运行其他linux发行版的软件包。

建议买个软路由

**Comment by jannson** [comment]
建议考虑我们的 ARS2 https://easepi.linkease.com
