### ISSUE TITLE
alist ipv6下无法访问

### ISSUE THREAD

**Issue by wangkerong** [linkease/istore-repo#479]
从istore商店下载的alist默认没有监听ipv6地址的5244端口，无法在ipv6下访问alist，请问如何配置修改？

**Comment by jjm2473** [comment]
alist的luci页面，勾选允许外网访问，应该就行了。如果还不行，就执行`/etc/init.d/alist restart`重启下alist

**Comment by jjm2473** [comment]
还有一个通用的ipv6转ipv4方法，就是安装istore里面的socat，配置个转发。

**Comment by wangkerong** [comment]
> alist的luci页面，勾选允许外网访问，应该就行了。如果还不行，就执行`/etc/init.d/alist restart`重启下alist

不行，端口我已经放行了，ipv6下根本访问不到。使用netstat查看就是没有监听ipv6地址的5244端口

**Comment by wangkerong** [comment]
> 还有一个通用的ipv6转ipv4方法，就是安装istore里面的socat，配置个转发。

这种不符合我的预期，ipv6可以远程在公网访问，ipv4下没公网ip

**Comment by wangkerong** [comment]
> @wangkerong 配置好以后重启下alist，过几秒钟执行下`netstat -anp|grep alist`把结果发出来

重启后可以访问了，感谢！
